#!/bin/sh

userresources=/tmp/.Xresources
usermodmap=/tmp/.Xmodmap
sysresources=/tmp/.Xresources
sysmodmap=/tmp/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

exec /usr/bin/grid-eye-demo

